config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :contacts
  resources :suppliers
  match('order_item/autocomplete' => 'order_items#autocomplete', :via => :get, :as => 'item_autocomplete')
  match('supplier/autocomplete' => 'suppliers#autocomplete', :via => :get, :as => 'supplier_autocomplete')


  resources :quotes
  resources :events
  resources :event_images
  devise_for :admins
  resources :admins

  resources :artists do
    resources :art_pieces
  end
  resources :baristas do
    resources :barista_photos
  end
  resources :places do
    resources :place_photos
  end
  root to: 'places#show', :id => 1

  get "current_art/index"
  match('current_art/' => 'current_art#index', :via => :get)
  match('current_art/labels' => 'current_art#labels', :via => :get)

  get "admin/index"
  match('admin/' => 'admin#index', :via => :get)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :post)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :get, as: 'approve_admins')
  match('admin/denied' => 'admin#denied', :via => :get)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/art_piece.rb
class ArtPiece < ActiveRecord::Base
  belongs_to :artist, inverse_of: :art_pieces
  validates :artist, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController
  before_action :set_art_piece, only: [:show, :edit, :update, :destroy]
  before_action :set_artist, only: [:new]
  before_action :authenticate_admin!, :except => [:show, :index]

  # GET /art_pieces
  # GET /art_pieces.json
  def index
    @art_pieces = ArtPiece.joins(:artist).order('art_pieces.currently_hanging desc, artists.name asc')
  end

  # GET /art_pieces/1
  # GET /art_pieces/1.json
  def show
  end

  # GET /art_pieces/new
  def new
    @art_piece = ArtPiece.new
  end

  # GET /art_pieces/1/edit
  def edit
  end

  # POST /art_pieces
  # POST /art_pieces.json
  def create
    @art_piece = ArtPiece.new(art_piece_params)

    respond_to do |format|
      if @art_piece.save
        format.html { redirect_to [@art_piece.artist], notice: 'Art piece was successfully created.' }
        format.json { render :show, status: :created, location: [@artist, @art_piecei] }
      else
        format.html { render :new }
        format.json { render json: @art_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_pieces/1
  # PATCH/PUT /art_pieces/1.json
  def update
    respond_to do |format|
      if @art_piece.update(art_piece_params)
        format.html { redirect_to [@art_piece.artist, @art_piece], notice: 'Art piece was successfully updated.' }
        format.json { render :show, status: :ok, location: [@art_piece.artist, @art_piece] }
      else
        format.html { render :edit }
        format.json { render json: @art_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_pieces/1
  # DELETE /art_pieces/1.json
  def destroy
    @art_piece.destroy
    respond_to do |format|
      format.html { redirect_to artist_art_ppieces_url, notice: 'Art piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_piece
      @art_piece = ArtPiece.find(params[:id])
      set_artist
    end

    def set_artist
      @artist = @art_piece.artist if !@art_piece.blank?
      @artist = Artist.find(params[:artist_id]) if (@artist.blank? && !params[:artist_id].blank?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_piece_params
      params.require(:art_piece).permit(:title, :media, :price, :needs_label, :currently_hanging, :can_display, :momo_percent, :artist_percent, :other_percent, :note, :artist_id, :image, :size)
    end
end

app/helpers/art_pieces_helper.rb
module ArtPiecesHelper
end

app/views/art_pieces/_display.html.erb
<% if (!size.blank? && (size == 'full')) %>
  <div class="PhotoWrapper FullImage">
<% else %>
  <div class="PhotoWrapper">
<% end %>
    <% if !@art_piece.image.blank? && (admin_signed_in? || @art_piece.can_display) %>
       <% if (!size.blank? && (size == 'full')) %>
         <div><%= image_tag @art_piece.image_url.to_s %></div>
       <% else %>
         <div><%= link_to image_tag(@art_piece.image_url(:thumb).to_s), [@artist, @art_piece] %></div>
       <% end %>
  <% else %>
    <div>
      <%= image_tag("noImageAvailable.jpg", alt: "no image available ") %>
    </div>
  <% end %>

  <div class="field">
    <span class="label">Title: </span> <span class="value"><%= @art_piece.title %></span>
  </div>

  <div class="field">
    <span class="label">Media: </span> <span class="value"><%= @art_piece.media %></span>
  </div>

  <div class="field">
    <span class="label">Size: </span> <span class="value"><%= @art_piece.size %></span>
  </div>

  <div class="field">
    <span class="label">Price: </span> <span class="value"><%= number_to_currency(@art_piece.price, unit: "$") %></span>
  </div>

  <% if (admin_signed_in?) %>
    <div class="AdminRegion">
      <div class="field">
        <span class="label"><%= @art_piece.needs_label ? "Needs Label" : "Has Label" %></span>
      </div>
      <div class="field">
        <span class="label"><%= @art_piece.can_display ? "Photo ok" : "Photo not good enough" %></span>
      </div>
      <div class="field">
        <span class="label"><%= @art_piece.currently_hanging ? "Currently Hanging" : "Not Hanging" %></span>
      </div>

  <div class="field">
    <span class="label">Momo Lolo %: </span> <span class="value"><%= @art_piece.momo_percent %></span>
    <span class="label">Artist %: </span> <span class="value"><%= @art_piece.artist_percent %></span>
    <span class="label">Other %: </span> <span class="value"><%= @art_piece.other_percent %></span>
  </div>

  <div class="field TextArea">
    <span class="label">Note: </span> <span class="value"><%= @art_piece.note.blank? ? "" :  @art_piece.note %></span>
  </div>
    <div><%= link_to "Edit Art Piece", edit_artist_art_piece_url(@artist, @art_piece) %></div>
    </div> <!-- AdminRegion -->
  <% end %>
</div> <!-- PhotoWrapper -->

app/views/art_pieces/_form.html.erb
<% @art_piece = ArtPiece.new if @art_piece.nil? %>
<% @artist = @art_piece.artist if @artist.blank? %>

<div class="PhotoWrapper">
<%= form_with model: [Artist, @art_piece], :html => {:multipart => true} do |f| %>
  <% if @art_piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art_piece.errors.count, "error") %> prohibited this art_piece from being saved:</h2>

      <ul>
      <% @art_piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Artist:' %>
    <%= f.collection_select(:artist_id, Artist.all, :id, :name, {prompt: 'Please select artist'}.merge(@artist.nil? ? {} : {selected: @artist.id})) %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :media %>
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, :value => (number_with_precision(f.object.price, :precision => 2) || 0), class: 'numeric_input' %>
  </div>

  <div class="field_group">
    <div class="field">
      <%= f.check_box :needs_label %>
      <%= f.label :needs_label %>
    </div>
    <div class="field">
      <%= f.check_box :can_display %>
      <%= f.label "Photo is good enough to display" %>
    </div>
    <div class="field">
      <%= f.check_box :currently_hanging %>
      <%= f.label "Currently Hanging" %>
    </div>
  </div>
  <div class="field_group">
    <div class="field">
      <%= f.label :momo_percent %>
      <%= f.number_field :momo_percent, class: 'numeric_input' %>
    </div>
    <div class="field">
      <%= f.label :artist_percent %>
      <%= f.number_field :artist_percent, class: 'numeric_input' %>
    </div>
    <div class="field">
      <%= f.label :other_percent %>
      <%= f.number_field :other_percent, class: 'numeric_input' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

    <% if !@art_piece.image.blank? %>
      <div>
        <%= image_tag @art_piece.image_url(:thumb).to_s %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div> <!-- PhotoWrapper -->
<% end %> <!-- form -->

app/views/art_pieces/edit.html.erb
<h1>Editing Art Piece</h1>

<div class="AdminPage">
  <%= render 'form' %>

  <%= link_to 'Show', [@artist, @art_piece] %> |
</div>

app/views/art_pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Art Pieces</h1>

<table class="index">
  <thead>
    <tr>
      <th>Title</th>
      <th>Media</th>
      <th>Price</th>
      <th>Needs label</th>
      <th>Currently hanging</th>
      <th>Momo %</th>
      <th>Artist %</th>
      <th>Other %</th>
      <th>Note</th>
      <th>Artist</th>
      <th colspan="3" class="action"></th>
    </tr>
  </thead>

  <tbody>
    <% @art_pieces.each do |art_piece| %>
      <tr>
        <td><%= art_piece.title %></td>
        <td><%= art_piece.media %></td>
        <td><%= art_piece.price %></td>
        <td><%= art_piece.needs_label %></td>
        <td><%= art_piece.currently_hanging %></td>
        <td><%= art_piece.momo_percent %></td>
        <td><%= art_piece.artist_percent %></td>
        <td><%= art_piece.other_percent %></td>
        <td><%= art_piece.note %></td>
        <td><%= art_piece.artist.name %></td>
        <td class="action"><%= link_to 'Show', [art_piece.artist, art_piece]  %></td>
        <td class="action"><%= link_to 'Edit', edit_artist_art_piece_path(art_piece.artist, art_piece) %></td>
        <td class="action"><%= link_to 'Destroy', [art_piece.artist, art_piece], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Art piece', new_artist_art_piece_path %>

app/views/art_pieces/new.html.erb
<h1>New Art Piece</h1>

<%= render 'form' %>

<%= link_to 'Back', artist_art_pieces_path %>

app/views/art_pieces/show.html.erb
<p id="notice"><%= notice %></p>

<div id="artists" class="TopWrapper">
  <div class="PhotoFilter">
    <h1>
      <%= link_to @artist.name, @artist %>
    </h1>
  </div>
</div>

<%= render partial: 'art_pieces/display', locals: {current_only: false, size: 'full'} %>