config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :contacts
  resources :suppliers
  match('order_item/autocomplete' => 'order_items#autocomplete', :via => :get, :as => 'item_autocomplete')
  match('supplier/autocomplete' => 'suppliers#autocomplete', :via => :get, :as => 'supplier_autocomplete')


  resources :quotes
  resources :events
  resources :event_images
  devise_for :admins
  resources :admins

  resources :artists do
    resources :art_pieces
  end
  resources :baristas do
    resources :barista_photos
  end
  resources :places do
    resources :place_photos
  end
  root to: 'places#show', :id => 1

  get "current_art/index"
  match('current_art/' => 'current_art#index', :via => :get)
  match('current_art/labels' => 'current_art#labels', :via => :get)

  get "admin/index"
  match('admin/' => 'admin#index', :via => :get)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :post)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :get, as: 'approve_admins')
  match('admin/denied' => 'admin#denied', :via => :get)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  default_scope { includes(:art_pieces).order("art_pieces.currently_hanging DESC, art_pieces.needs_label DESC, art_pieces.id DESC").references(:art_pieces) }

  has_many :art_pieces, dependent: :destroy, inverse_of: :artist
  accepts_nested_attributes_for :art_pieces, allow_destroy: true, reject_if: proc {|attributes| attributes[:first].blank? || attributes[:last].blank?}

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, :except => [:show, :index]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :phone, :web_site, :email, :instagram)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_display.html.erb
<h3>
  <% if (link_to_artist)  %>
    <%= link_to @artist.name, @artist %>
  <% else %>
    <%= @artist.name %>
  <% end %>
  <% if (!@artist.web_site.blank?) %>
     <a class="SocialIcon"
       href="<%= @artist.web_site %>"
       target="_blank">
       <%= image_tag("wwwIcon.jpg", alt: "web site link") %>
     </a>
  <% end %>
  <% if (!@artist.instagram.blank?) %>
     <a class="SocialIcon"
       href="<%= @artist.instagram %>"
       target="_blank">
       <%= image_tag("instagramLinkIcon.png", alt: "instagram link") %>
     </a>
  <% end %>
</h3>

<% if admin_signed_in? %>
  <div class="AdminRegion">
    <%= link_to 'Edit Artist', edit_artist_path(@artist) %> 
  </div>
  <div class="AdminRegion">
    <%= link_to 'New Art Piece', new_artist_art_piece_path(@artist) %>
  </div>
<% end %>

<% if (show_art && @artist.art_pieces.count > 0) %>
  <div class="ArtistPhotoDisplay">
    <div class="PhotoList">
      <% @artist.art_pieces.each do |piece| %>
        <% if (piece.currently_hanging || !current_only) %>
          <% @art_piece = piece %>
          <%= render partial: 'art_pieces/display', locals: {current_only: current_only, size: 'thumb' } %>
      <% end %>
    <% end %>
  </div> <!-- ArtistPhotoDisplay -->
<% end %>

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :artist_phone %>
  </div>

  <div class="field">
    <%= form.label :web_site %>
    <%= form.text_field :web_site, id: :artist_web_site %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :artist_email %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram, id: :artist_instagram %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div id="art" class="TopWrapper">
  <div class="PhotoFilter">
    <h2>Artist Info  - <%= @artist.name %></h2>
  </div>
</div>

<div class="AdminPage">
<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>
</div>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>
<div id="art" class="TopWrapper">
  <div class="PhotoFilter">
    <h1>Momo Lolo Art</h1>
    <h2>Everybody and Everything We've Had in the Shop</h2>
  </div>
</div> <!-- TopWrapper -->

<div>
  <%= link_to 'Current Art', current_art_index_path  %>
</div>

<% if !@artists.blank? %>
  <% @artists.each do |artist| %>
       <% @artist = artist %>
       <%= render partial: 'artists/display', locals: {current_only: false, show_art: true, link_to_artist: true} %>
  <% end %>
<% end %>

</div> <!-- artWrapper -->

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div id="artists" class="TopWrapper">
  <div class="PhotoFilter">
    <h1>
      <%= @artist.name %>
    </h1>
  </div>
</div>

<h3>
<% if (!@artist.web_site.blank?) %>
   <a class="SocialIcon"
     href="<%= @artist.web_site %>"
     target="_blank">
     <%= image_tag("wwwIcon.jpg", alt: "web site link") %>
     Web Site
   </a>
<% end %>
<% if (!@artist.instagram.blank?) %>
   <a class="SocialIcon"
     href="<%= @artist.instagram %>"
     target="_blank">
     <%= image_tag("instagramLinkIcon.png", alt: "instagram link") %>
   </a>
<% end %>
</h3>

<% if (@artist.art_pieces.count > 0) %>
  <div class="PhotoList">
    <% @artist.art_pieces.each do |piece| %>
       <% if admin_signed_in? || piece.currently_hanging %>
         <% @art_piece = piece %>
           <%= render partial: 'art_pieces/display', locals: {current_only: false, size: 'thumb' } %>
      <% end %>
    <% end %>
  </div> <!-- Art Pieces -->
<% end %>


<% if admin_signed_in? %>
  <div class="AdminRegion">
    <%= link_to 'Edit', edit_artist_path(@artist) %>
  </div>
  <div class="AdminRegion">
    <%= link_to 'New Art Piece', new_artist_art_piece_path(@artist) %>
  </div>
<% end %>