config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :contacts
  resources :suppliers
  match('order_item/autocomplete' => 'order_items#autocomplete', :via => :get, :as => 'item_autocomplete')
  match('supplier/autocomplete' => 'suppliers#autocomplete', :via => :get, :as => 'supplier_autocomplete')


  resources :quotes
  resources :events
  resources :event_images
  devise_for :admins
  resources :admins

  resources :artists do
    resources :art_pieces
  end
  resources :baristas do
    resources :barista_photos
  end
  resources :places do
    resources :place_photos
  end
  root to: 'places#show', :id => 1

  get "current_art/index"
  match('current_art/' => 'current_art#index', :via => :get)
  match('current_art/labels' => 'current_art#labels', :via => :get)

  get "admin/index"
  match('admin/' => 'admin#index', :via => :get)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :post)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :get, as: 'approve_admins')
  match('admin/denied' => 'admin#denied', :via => :get)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable

  def is_super_user?
     self.email == SUPER_ADMIN_EMAIL
  end

  def get_unapproved
    get_admins(false)
  end

  def get_approved
    get_admins(true)
  end

  def change_approval(admin_ids, value)
    Rails.logger.debug("Inside change approval admin_ids = #{admin_ids.inspect}")
    if (!self.is_super_user?) 
      return nil
    end
    (admin_ids || []).each do |a|
      admin = Admin.where(id: a).first
      if !admin.blank?
        Rails.logger.debug("Changing #{admin.name} approved = #{value.to_s}")
        admin.approved = value
        admin.save
        Rails.logger.debug("after save #{admin.inspect}")
      end
    end 
  end

  def active_for_authentication?
    super && (self.approved? || self.is_super_user?)
  end

  def inactive_message
    if !self.approved?
      :not_approved
    else
      super
    end
  end

private
  
  def get_admins(approval_status)
    if (!self.is_super_user?) 
      return nil
    end
    Admin.where(approved: approval_status)
  end
end

app/models/art_piece.rb
class ArtPiece < ActiveRecord::Base
  belongs_to :artist, inverse_of: :art_pieces
  validates :artist, presence: true

  mount_uploader :image, ImageUploader
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  default_scope { includes(:art_pieces).order("art_pieces.currently_hanging DESC, art_pieces.needs_label DESC, art_pieces.id DESC").references(:art_pieces) }

  has_many :art_pieces, dependent: :destroy, inverse_of: :artist
  accepts_nested_attributes_for :art_pieces, allow_destroy: true, reject_if: proc {|attributes| attributes[:first].blank? || attributes[:last].blank?}

end

app/models/barista.rb
class Barista < ApplicationRecord
#  default_scope { includes(:barista_photos).references(:barista_photos) }
  
  has_many :barista_photos, dependent: :destroy, inverse_of: :barista

  accepts_nested_attributes_for :barista_photos, allow_destroy: true, reject_if: proc {|attributes| attributes['image'].blank?}

  def full_name
    "#{first} #{last}"
  end
  
  def primary_photo
     barista_photos.where(primary_photo: true).order(created_at: :desc).limit(1).first
  end

end

app/models/barista_photo.rb
class BaristaPhoto < ApplicationRecord
  belongs_to :barista, inverse_of: :barista_photos
  validates :barista, presence: true

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :supplier
end

app/models/current_art.rb
class CurrentArt


  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor 

  def self.current_artists
    Artist.joins(:art_pieces).where("art_pieces.currently_hanging = true")
  end

  def self.needs_labels
    ArtPiece.where(needs_label: true) 
  end

  def needs_labels
    ArtPiece.where(needs_label: true) 
  end

  def self.attributes
    @attributes
  end

  def persisted?
    false
  end

  def self.inspect
    "#<#{ self.to_s} #{ self.attributes.collect{ |e| ":#{ e }" }.join(', ') }>"
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_image

  accepts_nested_attributes_for :event_image, reject_if: proc {|attributes| attributes[:first].blank? || attributes[:last].blank?}

  def format_event_dateXXX()
    if (event_start.strftime("%Y-%m-%d") == event_end.strftime("%Y-%m-%d"))
      rv = event_start.strftime("%A %B %e %l:%M%P") + event_end.strftime(" - %l:%M%P") 
    else
      rv = event_start.strftime("%A %B %e %l:%M%P") + event_end.strftime(" - %A %B %e %l:%M%P") 
    end
    return rv 
  end

  def html_event_dateXXX()
    if (event_start.strftime("%Y-%m-%d") == event_end.strftime("%Y-%m-%d"))
      rv = 
           '<div class="EventDateTime">' + 
             '<span class="Date">' + 
               event_start.strftime("%A %B %e") + 
             '</span>' + 
             '<span class="Time">' + 
               event_start.strftime("%l:%M%P") + event_end.strftime(" - %l:%M%P") +
             '</span>' + 
          '</div>'
    else
      rv = event_start.strftime("%A %B %e %l:%M%P") + event_end.strftime(" - %A %B %e %l:%M%P") 
           '<div class="EventDateTime">' + 
             '<span class="StartDate">' + 
                 event_start.strftime("%A %B %e %l:%M%P") + 
             '</span>' + 
             '<span class="EndDate">' + 
                event_end.strftime(" %A %B %e %l:%M%P") +
             '</span>' + 
          '</div>'
    end
    return rv 
  end
end

app/models/event_image.rb
class EventImage < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :events
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  default_scope { order(name: :asc) }

  has_many :supplier_items
  has_many :suppliers, through: :supplier_items

  accepts_nested_attributes_for :supplier_items, allow_destroy: true, reject_if: proc { |attributes| attributes['supplier_id'].blank? }
end

app/models/place.rb
class Place < ApplicationRecord
  default_scope { includes(:place_photos).order("place_photos.updated_at DESC").references(:place_photos) }

  has_many :place_photos, dependent: :destroy, inverse_of: :place
  accepts_nested_attributes_for :place_photos, allow_destroy: true, reject_if: proc { |attributes| attributes[:name].blank? }
end

app/models/place_photo.rb
class PlacePhoto < ApplicationRecord
  belongs_to :place, inverse_of: :place_photos
  validates :place, presence: true

  mount_uploader :image, ImageUploader
end

app/models/quote.rb
class Quote < ApplicationRecord

  def self.random_quote
    num_quotes = Quote.all.count
    quote = Quote.new(author: "everyone", quote_html: "Coffee makes everything better")
    if (num_quotes > 0)
      index = rand(num_quotes)
      quote = Quote.all[index]
    end
    return quote
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  default_scope { order(name: :asc) }
  has_many :contacts
  has_many :supplier_items
  has_many :order_items, through: :supplier_items

  accepts_nested_attributes_for :contacts, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }


end

app/models/supplier_item.rb
class SupplierItem < ApplicationRecord
  belongs_to :supplier
  belongs_to :order_item

  accepts_nested_attributes_for :supplier

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/admin/approve_admins.html.erb
<div id="main_container" class="AdminPage">

<h1>Approve Admins</h1>
<p>Approve (or disapprove) requests to be an administrator of the Momo Lolo site.</p>

<%=  form_tag('approve_admins', method: "post" ) do %>
<h2>Waiting for Approval</h2>

<% if @unapproved.blank? %>
     No unapproved requests.
<% else %>
     <table class="approval_table">
       <tr><th>Name</th><th>email</th><th>approve</th></tr>
<%       @unapproved.each do |u| %>
           <tr><td><%= u.name %></td><td><%= u.email %></td>
              <td><%= check_box_tag("approve[]", u.id) %></td>
           </tr>
<%       end %>
     </table>
<% end %>

<h2>Currently Approved</h2>
<% if @approved.blank? %>
      No approved requests.
<% else %>
     <table class="approval_table">
       <tr><th>Disapprove</th><th>Name</th><th>email</th></tr>
<%     @approved.each do |u| %>
          <tr><td><%= check_box_tag("disapprove[]", u.id) %></td>
          <td><%= u.name %></td><td><%= u.email %></td></tr>
<%     end %>
     </table>
<% end %>
  <div class="approval_submit">
  <%= submit_tag "Change Approvals", class: "submit_button" %>
  </div>

<%   end %> <!-- form -->
</div>

app/views/admin/denied.html.erb
<div id="main_container" class="AdminPage">
<h1>Access Denied</h1>

<p>
You are not allowed to access this functionality unless you are an approved admin for this site.
</p>

</div>

app/views/admin/index.html.erb
<div id="main_container" class="AdminPage">
<h1>Admin Actions</h1>

<% if current_admin.is_super_user? %>
<p><%= link_to 'Approve Admin Requests', approve_admins_path %> 
- Approve/Disapprove users who have requested permission to be site administrators.
</p>
<% end %>

</div>

app/views/admin/oldindex.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>