config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :contacts
  resources :suppliers
  match('order_item/autocomplete' => 'order_items#autocomplete', :via => :get, :as => 'item_autocomplete')
  match('supplier/autocomplete' => 'suppliers#autocomplete', :via => :get, :as => 'supplier_autocomplete')


  resources :quotes
  resources :events
  resources :event_images
  devise_for :admins
  resources :admins

  resources :artists do
    resources :art_pieces
  end
  resources :baristas do
    resources :barista_photos
  end
  resources :places do
    resources :place_photos
  end
  root to: 'places#show', :id => 1

  get "current_art/index"
  match('current_art/' => 'current_art#index', :via => :get)
  match('current_art/labels' => 'current_art#labels', :via => :get)

  get "admin/index"
  match('admin/' => 'admin#index', :via => :get)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :post)
  match('admin/approve_admins' => 'admin#approve_admins', :via => :get, as: 'approve_admins')
  match('admin/denied' => 'admin#denied', :via => :get)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  default_scope { includes(:place_photos).order("place_photos.updated_at DESC").references(:place_photos) }

  has_many :place_photos, dependent: :destroy, inverse_of: :place
  accepts_nested_attributes_for :place_photos, allow_destroy: true, reject_if: proc { |attributes| attributes[:name].blank? }
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place_display_photos = @place.place_photos.where(can_display: true).order(created_at: :desc).limit(6)
    set_notifications;
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end
  
   def set_notifications() 
     if (admin_signed_in?)
       active_clause = '1'
     else
       active_clause = 'active = true'
     end
     @notifications = Event.where('display_notify = true').
                            where(active_clause).
                            where('? > notify_start', DateTime.now).
                            where('? < notify_end', DateTime.now).
                            order('notify_start ASC')
  end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :street_address, :city_state)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: @place, local: true) do |form| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this @place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :place_name %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :place_street_address %>
  </div>

  <div class="field">
    <%= form.label :city_state %>
    <%= form.text_field :city_state, id: :place_city_state %>
  </div>

  <h1>Photos:</h1>
  <div class="NewPhotoLink">
    <%= link_to 'Create New Place Photo', new_place_place_photo_path(@place) %>
  </div>
  <% if @place.place_photos.count > 0 %>
    <div class="EditPhotoList">
      <% if @place.place_photos.count > 0 %>
        <% @place.place_photos.each do |photo| %>
          <div class="PhotoWrapper">
            <% @place_photo = photo %>
            <%= render partial: 'place_photos/form' %>
          </div>
        <% end %>
      <% end %>
    </div> <!-- EditPhotoList -->
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="AdminPage">
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>
</div> <!-- AdminPage -->

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street address</th>
      <th>City state</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.street_address %></td>
        <td><%= place.city_state %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<% if !@notifications.blank? %>
  <div class="PlaceNotifications">
    <% @notifications.each do |notification| %>
      <%= link_to notification.notify_title, notification, class: "Notification"%>
    <% end %>
  </div>
<% end %>

<div id="place">
<div id="placeWrapper">
  <div id="titleSection">
    <div>Coffee</div>
    <div>House</div>
  </div>
  
  <div id="hours">
    <div class="Hours">Weekdays 6:30 am – 10:00 pm</div>
    <div class="Hours">Weekends 7:30 am – 10:00 pm</div>
  </div>

  <div id="address">
    <div class="Address"><%= @place.street_address %></div>
    <div class="Address"><%= @place.city_state %></div> 
  </div>
</div> <!-- placeWrapper -->
</div> <!-- place -->

<div class="TitleDiv">
</div>
<div id="location">
<div id="locationWrapper">
  <div id="map">
    <iframe 
       src="https://www.google.com/maps/embed/v1/place?q=Momo%20Lolo%20Coffee%20House%2C%201129%20West%20Elizabeth%20Street%2C%20Fort%20Collins%2C%20CO%2C%20USA&key=AIzaSyAmtKV40lGmD1mVMp4RB9jXLXgltWQxXGQ" 
       allowfullscreen>
     </iframe>
  </div>

  <div id="comeVisit">
    <h1>COME VISIT US!</h1>
    <p class="BigParagraph">
       Located in the upbeat and popular area of Campus West. Come try our
       excellent espresso, coffee, tea, matcha... and spend time in our
       unique shop.
    </p>
  </div>
</div> <!-- locationWrapper -->
</div> <!-- location -->
<% if @place_display_photos.count > 0 %>
  <div class="owl-carousel owl-theme">
    <% @place_display_photos.each do |photo| %>
       <%= image_tag(photo.image_url(:thumb).to_s) %>
    <% end %>
  </div> <!-- carousel -->
  <div id="morePictures"><%= link_to "More Pictures", place_place_photos_path(@place) %></div>
<% end %> 